use std::{
    ffi::CString,
    marker::PhantomData,
    mem::MaybeUninit,
    ptr::{self, NonNull},
    rc::Rc,
};

use ort_genai_sys::{
    OgaCreateGenerator, OgaDestroyGenerator, OgaGenerator, OgaGenerator_AppendTokenSequences,
    OgaGenerator_AppendTokens, OgaGenerator_GenerateNextToken, OgaGenerator_GetInput,
    OgaGenerator_GetLogits, OgaGenerator_GetNextTokens, OgaGenerator_GetOutput,
    OgaGenerator_GetSequenceCount, OgaGenerator_GetSequenceData, OgaGenerator_IsDone,
    OgaGenerator_IsSessionTerminated, OgaGenerator_RewindTo, OgaGenerator_SetInputs,
    OgaGenerator_SetLogits, OgaGenerator_SetModelInput, OgaGenerator_SetRuntimeOption,
    OgaGenerator_TokenCount,
};

use crate::{
    error::{OgaResult, OgaResultExt},
    generator_params::GeneratorParams,
    impl_drop, impl_from_ptr, impl_into_ptr,
    model::Model,
    named_tensors::NamedTensors,
    sequences::Sequences,
    tensor::Tensor,
};

/// Generates tokens from a [`Model`] using [`GeneratorParams`].
pub struct Generator {
    ptr: NonNull<OgaGenerator>,
    _marker: PhantomData<Rc<()>>,
}

impl Generator {
    /// Creates a [`Generator`] from a [`Model`] and [`GeneratorParams`].
    ///
    /// # Parameters
    /// * `model` - The model to use for generation.
    /// * `params` - The parameters to use for generation.
    pub fn new(model: Model, params: GeneratorParams) -> OgaResult<Self> {
        let mut ptr = ptr::null_mut();

        unsafe { OgaCreateGenerator(model.into(), params.into(), &mut ptr) }.to_result()?;

        Self::try_from(ptr)
    }

    /// Returns `true` if the generator has finished generating all sequences.
    pub fn is_done(&mut self) -> bool {
        unsafe { OgaGenerator_IsDone(self.ptr.as_ptr()) }
    }

    /// Returns `true` if the generation session has been terminated.
    pub fn is_session_terminated(&self) -> bool {
        unsafe { OgaGenerator_IsSessionTerminated(self.ptr.as_ptr()) }
    }

    /// Sets an additional model input that is not handled by GenAI.
    ///
    /// For example, LoRA models can use additional model inputs for fine-tuning
    /// while GenAI handles the standard inputs.
    ///
    /// # Parameters
    /// * `name` - The model input name. It must match an input name in the model.
    /// * `tensor` - The tensor containing the input data.
    pub fn set_model_input(&mut self, name: &str, tensor: Tensor<'static>) -> OgaResult<()> {
        let name = CString::new(name)?;

        unsafe { OgaGenerator_SetModelInput(self.ptr.as_ptr(), name.as_ptr(), tensor.into()) }
            .to_result()
    }

    /// Sets additional model inputs that are not handled by GenAI.
    ///
    /// # Parameters
    /// * `named_tensors` - The named tensors to use as model inputs.
    pub fn set_inputs(&mut self, named_tensors: &NamedTensors) -> OgaResult<()> {
        unsafe { OgaGenerator_SetInputs(self.ptr.as_ptr(), named_tensors.into()) }.to_result()
    }

    /// Adds input ID sequences to the generator to seed generation.
    ///
    /// # Parameters
    /// * `sequences` - The input ID sequences to add.
    pub fn append_token_sequences(&mut self, sequences: &Sequences) -> OgaResult<()> {
        unsafe { OgaGenerator_AppendTokenSequences(self.ptr.as_ptr(), sequences.into()) }
            .to_result()
    }

    /// Adds input IDs to the generator to seed generation.
    ///
    /// # Parameters
    /// * `input_ids` - The input IDs to add. The slice length must match the
    ///   expected batch size multiplied by sequence length.
    pub fn append_tokens(&mut self, input_ids: &[i32]) -> OgaResult<()> {
        unsafe { OgaGenerator_AppendTokens(self.ptr.as_ptr(), input_ids.as_ptr(), input_ids.len()) }
            .to_result()
    }

    /// Returns the number of tokens added to the generator.
    pub fn token_count(&self) -> usize {
        unsafe { OgaGenerator_TokenCount(self.ptr.as_ptr()) }
    }

    /// Computes the next token logits from the model using the input IDs and
    /// past state, storing the computed logits in the generator.
    pub fn generate_next_token(&mut self) -> OgaResult<()> {
        unsafe { OgaGenerator_GenerateNextToken(self.ptr.as_ptr()) }.to_result()
    }

    /// Returns the next tokens generated by the model.
    ///
    /// The returned slice is owned by the generator and remains valid until
    /// the next generator operation that may update its token buffer.
    pub fn get_next_tokens(&self) -> OgaResult<&[i32]> {
        let mut tokens = ptr::null();
        let mut size = MaybeUninit::<usize>::uninit();

        unsafe { OgaGenerator_GetNextTokens(self.ptr.as_ptr(), &mut tokens, size.as_mut_ptr()) }
            .to_result()?;

        Ok(unsafe { std::slice::from_raw_parts(tokens, size.assume_init()) })
    }

    /// Sets a runtime option name and value.
    ///
    /// # Parameters
    /// * `key` - The runtime option name.
    /// * `value` - The runtime option value.
    pub fn set_runtime_option(&mut self, key: &str, value: &str) -> OgaResult<()> {
        let key = CString::new(key)?;
        let value = CString::new(value)?;

        unsafe { OgaGenerator_SetRuntimeOption(self.ptr.as_ptr(), key.as_ptr(), value.as_ptr()) }
            .to_result()
    }

    /// Rewinds the generator to the given token length so generation can
    /// continue from that point.
    ///
    /// Rewinding is not supported with beam search.
    ///
    /// # Parameters
    /// * `new_length` - The desired number of tokens after rewinding.
    pub fn rewind_to(&mut self, new_length: usize) -> OgaResult<()> {
        unsafe { OgaGenerator_RewindTo(self.ptr.as_ptr(), new_length) }.to_result()
    }

    /// Returns a CPU [`Tensor`] copy of the model input identified by `name`.
    ///
    /// The returned tensor owns its buffer and releases it when dropped.
    ///
    /// # Parameters
    /// * `name` - The name of the input tensor.
    pub fn get_input(&self, name: &str) -> OgaResult<Tensor<'static>> {
        let name = CString::new(name)?;
        let mut ptr = ptr::null_mut();

        unsafe { OgaGenerator_GetInput(self.ptr.as_ptr(), name.as_ptr(), &mut ptr) }.to_result()?;

        Tensor::try_from(ptr)
    }

    /// Returns a CPU [`Tensor`] copy of the model output identified by `name`.
    ///
    /// The returned tensor owns its buffer and releases it when dropped.
    ///
    /// # Parameters
    /// * `name` - The name of the output tensor.
    pub fn get_output(&self, name: &str) -> OgaResult<Tensor<'static>> {
        let name = CString::new(name)?;
        let mut ptr = ptr::null_mut();

        unsafe { OgaGenerator_GetOutput(self.ptr.as_ptr(), name.as_ptr(), &mut ptr) }
            .to_result()?;

        Tensor::try_from(ptr)
    }

    /// Returns a CPU [`Tensor`] copy of the logits from the model.
    ///
    /// The returned tensor owns its buffer and contains only the last-token
    /// logits, including during prompt processing.
    pub fn get_logits(&mut self) -> OgaResult<Tensor<'static>> {
        let mut ptr = ptr::null_mut();

        unsafe { OgaGenerator_GetLogits(self.ptr.as_ptr(), &mut ptr) }.to_result()?;

        Tensor::try_from(ptr)
    }

    /// Sets the logits used by the generator.
    ///
    /// This is useful for guided generation. The tensor must have the same
    /// shape as the tensor returned by [`Self::get_logits`].
    ///
    /// # Parameters
    /// * `tensor` - The tensor containing the last-token logits.
    pub fn set_logits(&self, tensor: Tensor<'static>) -> OgaResult<()> {
        unsafe { OgaGenerator_SetLogits(self.ptr.as_ptr(), tensor.into()) }.to_result()
    }

    /// Returns the number of tokens in the sequence at `index`.
    ///
    /// # Parameters
    /// * `index` - The sequence index.
    pub fn get_sequence_count(&self, index: usize) -> usize {
        unsafe { OgaGenerator_GetSequenceCount(self.ptr.as_ptr(), index) }
    }

    /// Returns the token data for the sequence at `index`.
    ///
    /// The returned slice is owned by the generator and remains valid until
    /// the generator is destroyed. Copy the data if it must be used after the
    /// generator is dropped.
    ///
    /// # Parameters
    /// * `index` - The sequence index.
    pub fn get_sequence_data(&self, index: usize) -> &[i32] {
        let ptr = unsafe { OgaGenerator_GetSequenceData(self.ptr.as_ptr(), index) };

        unsafe { std::slice::from_raw_parts(ptr, self.get_sequence_count(index)) }
    }
}

impl_from_ptr! {Generator, OgaGenerator}
impl_into_ptr! {Generator, OgaGenerator}
impl_drop! {Generator, OgaDestroyGenerator}
